import { Suspense } from 'react';
import WordCompare from './WordCompare';

type Props = {
  params: {
    slug: string;
  };
};

export function generateMetadata({ params }: Props) {
  const { slug } = params;

  return {
    title: `${slug} - Tracinho.online`,
    description: 'Generated by create next app',
  };
}

export default function Page({ params }: Props) {
  const { slug } = params;

  return (
    <Suspense fallback={<div>Carregando...</div>}>
      <WordCompare slug={slug} />
    </Suspense>
  );
}
