import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './global.css';
import { twMerge } from 'tailwind-merge';
import { ApolloWrapper } from '@tracinho/graphql';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tracinho',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const classNames = twMerge('h-full', inter.className);

  return (
    <html lang="en" className="h-full">
      <body className={classNames}>
        <div className="min-h-full">
          <ApolloWrapper>{children}</ApolloWrapper>
        </div>
      </body>
    </html>
  );
}
